### ISSUE TITLE
The VertexLit shaders fail to Build in Unity for the UWP Win 10 HoloLens with light baking

### ISSUE THREAD

**Issue by teichgraf** [Microsoft/HoloToolkit-Unity#22] opened 2016-04-29 06:49 UTC
The HoloToolKit VertexLit shaders fail to Build in Unity for the UWP Win 10 HoloLens target when light baking is turned on: 

Error building Player: Shader error in 'HoloToolkit/Vertex Lit Configurable': invalid subscript 'texcoord1' at Assets/HoloToolkit/Shaders/VertexLitConfigurable.cginc(67) (on d3d11)

Compiling Vertex program with DIRECTIONAL SHADOWS_OFF LIGHTMAP_ON DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF
Platform defines: UNITY_NO_SCREENSPACE_SHADOWS UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF3 UNITY_HARDWARE_TIER1

**Comment by NeerajW** [comment] 2016-05-03 21:40
@teichgraf thanks Rene for filing this. Do you have a proposal to fix this? Would you like to try to fix this?

**Comment by teichgraf** [comment] 2016-06-16 13:35
Is this being worked on or does it make sense to investigate a fix proposal?

**Comment by NeerajW** [comment] 2016-06-17 17:00
@teichgraf do you have a proposed fix for this? Would you like to fix this?

**Comment by ignavus** [comment] 2016-11-29 13:12
I am no shader expert by any mean, but I encountered this, as I far as I understand the texcoord1 is the texture of the lightmap that will be sent to the shader along with its normal texture in the case of having lightmap enabled
The problem is while texcoordis that texcoord1 is not defined in the appdata_t struct in the file "VertexLitConfigurable.cginc" so when trying to access it while having baked GI enabled it results in that error, when I added the following lines to the file after the definition of texcoord. it worked fine
```
struct appdata_t
{
    float4 vertex   : POSITION;
    #if _USEMAINTEX_ON || _USEEMISSIONTEX_ON
        float2 texcoord : TEXCOORD0;
    #endif

	#if DYNAMICLIGHTMAP_OFF || !LIGHTMAP_OFF
		float2 texcoord1 : TEXCOORD1;
	#endif
    float3 normal : NORMAL;
};

```

Again I am no shader expert, and this may cause bugs I am not aware of

**Comment by HodgsonSDAS** [comment] 2017-01-24 22:43
@teichgraf, there was some shader updates recently.  Has those updates resolved this issue?

@ignavus Would you be willing to submit a PR with those fixes you've detailed?

**Comment by HodgsonSDAS** [comment] 2017-02-03 15:47
@dbastienMS did your recent updates fix this?

**Comment by StephenHodgson** [comment] 2017-08-01 00:57
New shaders have fixed this issue.

**Closed by StephenHodgson** 2017-08-01 00:57 UTC
Labels: Bug
