### ISSUE TITLE
Autodiscovery (sharingmanager) isn't working 

### ISSUE THREAD

**Issue by DrNeuroSurg** [Microsoft/HoloToolkit-Unity#505] opened 2017-02-06 15:55 UTC
Again:
The Sharing test scene: Setting AutoDiscoverServer = true **and** leaving the Server-Address empty there is no server found (not locally, nor remote - even in the same subnet).

This worked with schema 15 ... !
See #491

**Comment by HodgsonSDAS** [comment] 2017-02-06 15:59
Duplicate of https://github.com/Microsoft/HoloToolkit-Unity/issues/493

**Closed** 2017-07-12 21:29 UTC
Labels: Duplicate
