### ISSUE TITLE
Cursor  disappears  when i gaze at the UGUI Canvas

### ISSUE THREAD

**Issue by sunt89** [Microsoft/HoloToolkit-Unity#573] opened 2017-03-21 04:09 UTC
I create a  UGUI Gameobject, And add box collider on it.  When I  gaze at the canvas, sometimes the cursor appear,     sometimes The Cursor  disappears.   It seems like the cursor gameobject hide behide the UGUI gameobject.  I do not know what is wrong.

**Comment by chadbramwell** [comment] 2017-03-23 21:01
Hi sunt89,

Sorry for the late reply, which Cursor you using? Sadly there's a ton of them... so here's some possible answers:

**Prefabs: (found in Input/Prefabs/Cursor)**
- BasicCursor
- Cursor
- CursorWithFeedback
- DefaultCursor

**Components: (found in Input/Scripts/Cursor)**
- AnimatedCursor
- Cursor
- MeshCursor
- ObjectCursor
- SpriteCursor

**Comment by mattfedocsg** [comment] 2017-03-23 21:22
I noticed this as well. Things to check here.

1) Check your canvas order.  Sometimes your canvases will be in front of the cursor or greater than 0.  Or if they are negative, it might miss the canvas all together.
2) Make sure your UI element has raycast targeting active on it.
3) When in doubt place a collider behind it.  It will float in front of the UI element because of the collisions.

**Comment by chadbramwell** [comment] 2017-03-23 21:37
Ah, I think I've repro-ed an issue: for some reason, ObjectCursor.OnEnable loops through all children and disables them. No children will become visible until at least one object has been successfully raycasted against. @LocalJoost could you provide some context for what's going on here?

**Comment by sunt89** [comment] 2017-03-24 01:04
@chadbramwell hi, thanks for your reply, I am using the cursor  prefab, the path is  Input/Prefabs/Cursor/Cursor.   And i am not using a CursorModifier.

**Comment by sunt89** [comment] 2017-03-24 01:19
@mattfedocsg  hi, thanks for your reply. 
1. I checked my canvas order, its layer is UI, and order in layer is 0.   If  i set the order in layer with -1, the cursor will not disappear on the canvas, but this setting will cause other issue, things behide the canvas can be seen through the canvas. 
2. UI element has raycast targeting active on it
3. I palce a box collider on it ,not behind it.

**Comment by chadbramwell** [comment] 2017-03-24 17:00
@sunt89 thanks for your reply!

I've been able to reproduce your issue. It looks like a very common rendering order issue - both the cursor and the ui elements are in the Transparent RenderQueue (value of 3000). Because of that, they are sorted by center of object to camera. Which ever object's center is closer to the camera will get rendered last causing the strange disappearing issues you describe.

Here's a quick fix you can try until a real solution gets added to HTK:

Open \Input\Shaders\EditorHands.shader
Comment-out this line at the bottom of the file: CustomEditor "EditorHandsMaterialInspector"

That will make this item outlined in red appear:
![image](https://cloud.githubusercontent.com/assets/2281861/24304969/90c320f6-1078-11e7-9ea6-6a32ac27ef68.png)

Next, change that Render Queue value to be greater than 3000. Once that happens it'll force all transparent objects (the UI) to be rendered before the cursor.

@StephenHodgson or someone else, could we mark this as a bug?

**Comment by StephenHodgson** [comment] 2017-03-24 18:21
I'd suggest using the [DefaultCursor.prefab](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Prefabs/Cursor/DefaultCursor.prefab). Pretty sure those old cursors are technically depreciated.

If you're creating your own custom cursor, then simply adjust the render queue to the appropriate depth.

**Comment by LocalJoost** [comment] 2017-03-24 19:05
Hi,

I always use the normal Cursor prefab,, is that deprecated as well?

Joost van Schaik

Windows Development MVP
Sent from Mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by StephenHodgson** [comment] 2017-03-25 00:32
I mean they're still there, but it was my impression that the mesh cursors were added to replace the ones @sunt89 was using.

**Comment by sunt89** [comment] 2017-03-25 01:08
@chadbramwell  Thanks for your solution, I tried it, and it works.

**Comment by sunt89** [comment] 2017-03-25 01:09
@StephenHodgson  Thanks for your reply, And I will try to use the DefaultCursor.prefab.

**Closed** 2017-03-26 01:59 UTC

**Comment by Chefty** [comment] 2017-09-18 14:44
None of the solution above really worked for me.

I had to change some HololensCamera settings:
Clipping Planes Near : 0.01
Rendering Path : "Use Graphics Settings"

Hope it will also help someone else.

**Comment by StephenHodgson** [comment] 2017-09-18 15:09
@Chefty Sounds like it was just too close to the camera.
