### ISSUE TITLE
GameControllerManipulator needs HandsManager.cs to avoid null ref

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#302] opened 2016-10-21 16:45 UTC
https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/GameControllerManipulator 

Uses a cursor which responds to Hands feedback but is missing attaching HandsManager.cs to the Managers gameobject.

Was this scene created using Unity 5.5? Something seems not backwards compatible with Unity 5.4?

**Comment by HodgsonSDAS** [comment] 2016-10-21 19:09
![image](https://cloud.githubusercontent.com/assets/13334553/19608557/24a175ea-97a0-11e6-90bd-c0671d80e112.png)

Seem to be missing game objects in the Editor as well.
This is strange because I tested this scene and didn't have this problem before it was merged in.
@vbandi thoughts?

**Comment by xaviercrespin** [comment] 2016-10-21 19:13
I can confirm that i have tested it 20 minutes ago, and objects were missing too

**Comment by HodgsonSDAS** [comment] 2016-10-21 19:15
They're there but it seems like the meta data got stripped off somehow.

**Comment by HodgsonSDAS** [comment] 2016-10-21 19:42
I replaced the `CursorWithFeedback.prefab` with just the regular `Cursor.prefab`.  Tested on device.

**Comment by HodgsonSDAS** [comment] 2016-10-21 20:05
I've got both `Bluetooth` and `HumanInterfaceDevice` capabilities flagged as true, but no dice.  Does `Independant Input Source` also need to be true?

**Comment by NeerajW** [comment] 2016-10-24 16:12
Yeah this scene worked on beta 5.5 but not on 5.4.

@vbandi can you please work on a fix?

**Comment by HodgsonSDAS** [comment] 2016-10-24 16:30
Ahh, Then I think just replacing the CursorWithFeedback.prefab with just the regular Cursor.prefab will prevent the null ref.

**Comment by HodgsonSDAS** [comment] 2016-12-02 16:09
This is now depreciated because of the new Input Architecture.

**Comment by keveleigh** [comment] 2016-12-07 20:49
@HodgsonSDAS So this Issue can be closed in favor of #362?

**Comment by HodgsonSDAS** [comment] 2016-12-07 20:54
Correct

**Closed** 2016-12-07 20:58 UTC
Labels: bug
