### ISSUE TITLE
Spatial Mapping is crashing in HoloLens device

### ISSUE THREAD

**Issue by hariragavanInoryasoft** [Microsoft/HoloToolkit-Unity#291] opened 2016-10-18 07:04 UTC
Usage of "Spatial Mapping" prefab under HoloToolkit/SpatialMapping/Prefabs/SpatialMapping.prefab is making the app crash in HoloLens device. Without the Spatial Mapping prefab app works fine.

**Comment by NeerajW** [comment] 2016-10-18 16:35
I just tried the SpatialProcessing.unity test scene under SpatialMapping\Tests folder and it worked for me.

Could you please share more details about your repro? Perhaps a stack that might help pinpoint the issue?

**Comment by darax** [comment] 2016-10-18 19:34
Did you enable the spatialperception capability?

**Comment by kaiomagalhaes** [comment] 2016-10-19 01:37
I'm having issues with the current spatial mapping and processing. It seems to work fine in unity but once I deploy it to the emulator it doesn't work. I'm not being able to see the meshes or the planes.

Also the SpatialMapping tests are not working in the emulator.

And yeah, the spatial perception is enabled

@NeerajW did you test it in unity or in the emulator?

**Comment by hariragavanInoryasoft** [comment] 2016-10-19 04:31
@darax - I enabled Spatial Perception. I am not able to narrow down the problem. Sometimes its working sometimes its crashing and home screen comes. 

@NeerajW - I will give it a try. As I said. Sometimes its working perfect sometimes its not. I would like to know how to optimize it to perfect level. Presently what I am doing to optimize is that, I increased Update Time (so that it doesn't take more performance) and I reduced the distance of how much it should spatial map. Is there any other ways to optimize ??

**Comment by darax** [comment] 2016-10-19 16:35
When it crashes, it should break into the debugger.  You may need to change your debug settings to mixed (managed and native). Otherwise you might need to enable crash dumps from the App Crash Dumps tab in the developer portal webpage.

How you would optimally tune it depends on how you are using the surfaces.  Many apps choose to scan surfaces during the initial part of the application and then turn scanning off when the user affirms that the scan looks good.  

Another way to reduce the cost of spatial mapping is to not render the surfaces.

**Comment by kaiomagalhaes** [comment] 2016-10-19 16:54
For me not even the spatial processing tests are working, so I don't believe it is something with processing cost.

**Comment by darax** [comment] 2016-10-19 21:10
@kaiomagalhaes  I think you have a separate issue than the OP.  I have a repro, and I think I know how to fix it, but the side effect wouldn't be a crash (as the OP), it would be that you simply didn't get surfaces.

**Comment by kaiomagalhaes** [comment] 2016-10-20 02:29
You mean that I wouldn't be able to recognize the surfaces in the emulator/device? =/

**Comment by hariragavanInoryasoft** [comment] 2016-10-20 05:29
@darax - Thanks. That was very helpful. I was rendering the surface also (may be that's why its crashing). I enabled the app crash dump. I will give it a try and see. Thanks for the help.

**Comment by darax** [comment] 2016-10-20 17:00
@kaiomagalhaes on the device the test scene should work. On the emulator it probably depends on how fast your computer is.  I'm not sure what the root cause is, but I've got a workaround that I'm testing.

**Comment by kaiomagalhaes** [comment] 2016-10-20 17:02
Awesome @darax thanks! In my emulator it is supposed to work since it is working with the old version. I'm going to test it now and I let you know.

**Comment by darax** [comment] 2016-10-20 17:08
k, if it doesn't work, I think the fix is in SpatialMappingObserver.cpp, you can replace the StartObserving function with:

/// <summary>
        /// Starts the Surface Observer.
        /// </summary>
        public void StartObserving()
        {
            if (ObserverState != ObserverStates.Running)
            {
                // on device, this isn't necessary, but sometimes in the emulator the observer 
                // won't realize that it hasn't already sent you the surfaces, and since the surfaces
                // don't really get updated in the emulator you'll end up getting no surfaces at all.
                if (surfaces.Count == 0)
                {
                    if (observer != null)
                    {
                        observer.Dispose();
                        observer = null;
                    }

                    observer = new SurfaceObserver();
                }

                ObserverState = ObserverStates.Running;

                // We want the first update immediately.
                updateTime = 0;
            }
        }

**Comment by kaiomagalhaes** [comment] 2016-10-20 17:28
@darax tested in the emulator and it works fine!

**Comment by NeerajW** [comment] 2016-10-24 23:34
I believe a PR fixed this?

**Comment by darax** [comment] 2016-10-24 23:38
@hariragavanInoryasoft  The PR I did was for kaiomagalhaes' issue, which is different.  @hariragavanInoryasoft, if you are still having trouble, can you open another issue?

**Comment by hariragavanInoryasoft** [comment] 2016-10-25 08:37
@NeerajW  and @darax . No. I will close this issue. Mine is fixed.

**Comment by hariragavanInoryasoft** [comment] 2016-10-25 08:41
actually i don't think i can close this now.. can somebody commit a fix ? or i have to do it ?

**Closed** 2016-10-25 16:49 UTC
Labels: bug

**Comment by DanTDMMcpe** [comment] 2017-05-11 12:48
I have this problem

an error of access violation
