### ISSUE TITLE
Hand draggable changes object's rotation when it shouldn't

### ISSUE THREAD

**Issue by 8greg8** [Microsoft/HoloToolkit-Unity#525] opened 2017-02-20 09:05 UTC
Let's say I use Hand Draggable script to move some cylinder which it lies on a plane (Z rotation 90°). Is Keep Upright and Is Orient towards user are unchecked. 

When I click on it in Game mode to move it, it changes rotatation to upwards (Z rotation 0°).

Shouldn't the lines 199 and 200 in Hand Draggable script simply be:

`draggingRotation = HostTransform.rotation;`

**Comment by cnspaha** [comment] 2017-02-20 09:06
probably duplicate of #519 ?

**Comment by HodgsonSDAS** [comment] 2017-02-20 14:03
Yeah this has been fixed with @cnspaha's pull request.

**Comment by HodgsonSDAS** [comment] 2017-02-21 14:27
@8greg8 is this issue closed?

**Comment by 8greg8** [comment] 2017-02-21 17:32
Pulled the latest and everything works now. @HodgsonSDAS the issue is closed.

**Closed** 2017-02-21 17:33 UTC
