### ISSUE TITLE
Autodiscover server not working

### ISSUE THREAD

**Issue by sebrk** [Microsoft/HoloToolkit-Unity#755] opened 2017-07-04 13:13 UTC
I've been trying to get the UNet sharing examples to work. In fact I've been trying to get connections to the Hololens to work for a couple of days. So far I've tried:

- UDP server/client (UWP). Works flawless in Windows 10 and other devices.
- UNet dito. Also works fine on other devices.
- HoloToolkit SharingTest scene with autodiscover (on device and on localhost)
- I have tried on multiple routers, even with the server running ON the router itself.

The ONLY thing that works seems to be the SharingTest scene IF I disable Auto Discover Server setting and fill in a specific IP address. 

But that is not what I need. I need a flexible system hence me trying to get a UDP broadcast working.

All Capabilities are set and no firewalls are interupting. On ALL of the above I can clearly see the packets on the network.

This makes me wonder if there is a firewall blocking on the Hololens? I'm on the way of giving this up. It seems the Hololens does in fact not follow the UWP standard. Can anyone point me in the right direction?

Of course the above should also be considered a bug report. Just opening the scene and running it I find no servers, even on localhost.

**Comment by StephenHodgson** [comment] 2017-07-04 16:28
@sebrk see https://github.com/Microsoft/HoloToolkit/issues/70

**Comment by StephenHodgson** [comment] 2017-07-04 16:30
Also duplicate of https://github.com/Microsoft/HoloToolkit-Unity/issues/493

**Closed** 2017-07-12 21:28 UTC
Labels: Duplicate
