### ISSUE TITLE
Readme.md need to be updated

### ISSUE THREAD

**Issue by Xwil** [Microsoft/HoloToolkit-Unity#431] opened 2016-12-24 04:15 UTC
some scripts or prefabs have already changed in HoloToolkit, but readme.md is still old.
such as GestureManipulator.cs and Main Camera.prefab etc..

**Comment by HodgsonSDAS** [comment] 2016-12-24 04:27
This is a partial duplicate of https://github.com/Microsoft/HoloToolkit-Unity/issues/380 and PR https://github.com/Microsoft/HoloToolkit-Unity/pull/376 has been submitted already.

Would you like me to address the GestureManipulator update, or would you be kind enough to submit a PR on my fork to get it submitted with the open PR?

**Comment by HodgsonSDAS** [comment] 2016-12-24 04:52
@Xwil was there anything else I missed that needs to be updated?

**Comment by Xwil** [comment] 2016-12-24 04:55
@HodgsonSDAS thanks

**Comment by Xwil** [comment] 2016-12-24 05:09
@HodgsonSDAS I can't find GestureManipulator.cs in HoloToolKit, all I can find about Gesture is (InputManager/GestureInput) GestureInput.cs and GestureResponder. and I added GestureResponder to my gameobject, I want to scale my gameobject by Gesture.What should I do?
I also add Hand Draggable.cs to my gameobject, it works fine.
Sorry to bother you  , I'm new to Hololens , and I'm confused about HoloToolKit.Thanks a lot.

**Comment by aalmada** [comment] 2016-12-24 10:26
@Xwil To handle gestures you need to have one InputManager and at least one GestureInput in your scene. To handle the events, the MonoBehaviours that handle them have to implement any of these (one or more), depending on what you are interested: IInputClickHandler, IHoldHandler, IManipulationHandler, INavigationHandler.
The InputManager calls the handler that is at the GameObject with the gaze focus. If there is none, it goes up the scene hierarchy until it finds one or gives up pass the root. If you want the handler to be always called, register it with the InputManager as a global listener: 
''' csharp
Start()
{
  InputManager.Instance.AddGlobalListener(gameObject);
}
'''

**Comment by Xwil** [comment] 2016-12-25 01:50
@aalmada Thank you so much,I'll try it.

**Closed** 2017-01-14 16:31 UTC

**Comment by comarabi** [comment] 2017-04-04 15:00
@aalmada I can`t implement the handler on the Gameobject. I get the the error "cant add the script behaviour.... the script class cant be abstract!"
what the issue? Thanks for helping, sorry I m new in developing....
